apiVersion: apps/v1
kind: Deployment
metadata:
  name: duydeptrai1
spec:
  selector:
    matchLabels:
      app: duydeptrai3
  replicas: 2
  template:
    metadata:
      labels:
        app: duydeptrai3
    spec:
      containers:
        - name: duydeptrai4
          image: nanajanashia/argocd-app:1.0
          ports:
            - containerPort: 8080
