apiVersion: apps/v1
kind: Deployment
metadata:
  name: duydeptrai
spec:
  selector:
    matchLabels:
      app: duydeptrai
  replicas: 2
  template:
    metadata:
      labels:
        app: duydeptrai
    spec:
      containers:
        - name: duydeptrai
          image: nanajanashia/argocd-app:1.0
          ports:
            - containerPort: 8080
